config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'employees#index', as: 'home'
  get 'about' => 'pages#about'
  resources:employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def index
		@employee = Employee.all
	end
	def new
		@employee = Employee.new
	end
	def show
		@employee = Employee.find(params[:id])
	end
	def create
		#render plain:params[:employee].inspect
		@employee = Employee.new(employee_params)
		@employee.save
		redirect_to @employee
	end
	def edit
			@employee = Employee.find(params[:id])
	end
	def update
		@employee = Employee.find(params[:id])
		@employee.update(employee_params)
		redirect_to @employee
	end
	def destroy
		@employee = Employee.find(params[:id])
		@employee.destroy
		redirect_to @employee
	end
	private def employee_params
		params.require(:employee).permit(:name, :age, :designation,:gender)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title ="about ...";
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/edit.html.erb
<h1>Edit Employees</h1>
<%= form_for @employee do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>	
	</p>
	<p>
		<%= f.label :age %>
		<%= f.text_field :age %>	
	</p>
	<p>
		<%= f.label :designation %>
		<%= f.text_field :designation %>	
	</p>
	<p>
		  <%= f.label :gender %>
		<%= f.text_field :gender %> 
	</p>
	<p>
	<%= f.submit({:class => 'btn  btn-primary'}) %>
	</p>
<% end %>

app/views/employees/index.html.erb
<h2>Employee details</h2>
<% @employee.each do |emp| %>
	<h1><%= emp.name %></h1>
	<h6>Designation:<%= emp.designation %></h6>
	<%= link_to "show" ,emp,{:class => 'btn btn-lg btn-primary'} %>
	<hr>
<% end %>

app/views/employees/new.html.erb
<h2>Add Employees</h2>
<hr>
<%= form_for @employee do |f| -%>

	<%  if @employee.errors.any? %>
		<% @employee.errors.full_messages.each do |msg|  %>
		<div class="alert alert-danger"><%= msg %></div>
		<% end %>
		<% end %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>	
	</p>
	<p>
		<%= f.label :age %>
		<%= f.text_field :age %>	
	</p>
	<p>
		<%= f.label :designation %>
		<%= f.text_field :designation %>	
	</p>
	<p>
		<%= f.label :gender %>
		<%= f.text_field :gender %> 
	</p>
	<p>
	<%= f.submit({:class => 'btn  btn-primary'}) %>
	</p>
<% end %>

app/views/employees/show.html.erb
<h2>Name:<%= @employee.name %><br></h2>
	<p>Age:<%= @employee.age %><br>
	Gender:<%= @employee.gender %><br>
	Designation:<%= @employee.designation %><br>
	</p>
	<hr>
	<%= link_to "Edit" ,edit_employee_path,:class => 'btn btn-primary' %>
<%= link_to "Delete" ,@employee, method: :delete,data:{confirm: 'Are you sure?'},:class => 'btn  btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeApp</title>
    <%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="#">My Employee</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
             <%= link_to "Home", home_path,{:class => 'nav-link'} %>
          </li>
          <li class="nav-item active">
            <%= link_to "Create Employees", new_employee_path,{:class => 'nav-link'} %>
          </li>
         
        </ul>
       
      </div>
    </nav>

    <main role="main" class="container">
      <div class="jumbotron">
        <%= yield %>
      </div>
    </main>


  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>